services:
  mateonunez_frontend_nextjs:
    container_name: mateonunez_frontend_nextjs
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: dev
    working_dir: /app
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - /app/.next
      - .:/app
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml
    networks:
      - mun_network

networks:
  mun_network:
    driver: bridge
